# Generated by Django 4.0.4 on 2022-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='sadasd', max_length=125),
            preserve_default=False,
        ),
    ]
